version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jadwal_sholat
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/jadwal-sholat/node_modules
      - /app/packages/eslint-config-custom/node_modules
